apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-telegram-data
  namespace: {{ include "video-app.namespace" . }}
  labels:
    {{- include "video-app.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.backend.telegramSession.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.telegramSession.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: video-local-storage
  namespace: {{ include "video-app.namespace" . }}
  labels:
    {{- include "video-app.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  {{- with .Values.backend.localStorage.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.localStorage.size }}
